### ISSUE TITLE
COUS Model

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz-ws#4]
If the web application determines the model should be COUS, the web service seems not to know how to handle it...

```
java.lang.IllegalArgumentException: No enum constant gov.usgs.earthquake.nshm.www.services.Model.COUS_2008
    at java.lang.Enum.valueOf(Enum.java:236)
    at gov.usgs.earthquake.nshm.www.services.Model.valueOf(Model.java:10)
    at gov.usgs.earthquake.nshm.www.services.HazardCurve.processCalculation(HazardCurve.java:140)
    at gov.usgs.earthquake.nshm.www.services.HazardCurve.doGet(HazardCurve.java:97)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:301)
    at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:165)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

Not sure about best method to resolve this since there is no "COUS_*" model repo.

**Comment by pmpowers-usgs** [comment]
Fixed in fdfe58cccf1d66c2d233e65af0831713b2cf1a2f. Pushed to @pmpowers-usgs and pulled to upstream along with other changes by @emartinez-usgs
